on:
  workflow_call:
  
  
jobs:
  setup_jdk:
    runs-on: ubuntu_latest
    steps:
    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
    
    
